# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"levenshtein_distance": "00_algos.ipynb"}

modules = ["algos.py"]

doc_url = "https://ncoop57.github.io/cute_deltas/"

git_url = "https://github.com/ncoop57/cute_deltas/tree/main/"

def custom_doc_links(name): return None
